// Sound cues on the 120 BPM grid (beat = 0.5 s). tools/sfx.mjs synthesizes these.
export const CUES = [
  { t: 0.0, type: 'thump' },
  { t: 0.5, type: 'tick' },
  { t: 1.0, type: 'roll' },
  { t: 1.5, type: 'pop' },
  { t: 2.0, type: 'whoosh' },
  { t: 2.25, type: 'tick' }, { t: 2.5, type: 'tick' }, { t: 2.75, type: 'tick' }, { t: 3.0, type: 'tick' },
  { t: 4.0, type: 'whoosh' },
  { t: 4.5, type: 'click' },
  ...[4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2].map(t => ({ t, type: 'key' })),
  { t: 5.5, type: 'click' },
  { t: 6.0, type: 'whoosh' },
  { t: 7.0, type: 'pop' },
  { t: 7.5, type: 'tick' },
  { t: 8.0, type: 'tick' },
  { t: 8.25, type: 'roll' },
  { t: 9.0, type: 'whoosh' },
  { t: 9.5, type: 'click' },
  { t: 10.0, type: 'whoosh' },
  { t: 12.0, type: 'thump' },
  { t: 14.25, type: 'click' },
  { t: 14.5, type: 'whoosh' },
  { t: 15.0, type: 'pop' },
  { t: 16.0, type: 'whoosh' },
  { t: 16.0, type: 'roll' },
  { t: 16.75, type: 'tick' },
  { t: 18.0, type: 'thump' },
  { t: 18.5, type: 'tick' },
  { t: 19.0, type: 'tick' },
];
